version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: backend_app
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3005:3005"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  frontend:
    build:
      context: ../front-end  # Chemin vers le dossier contenant le projet Nuxt.js
    container_name: frontend_app
    restart: always
    ports:
      - "3001:3000"  
    volumes:
      - ../front-end:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - app

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: