
services:
  db:
    image: postgres:latest
    container_name: postgres_database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_database:/var/lib/postgresql/data
      - ./models/schema.sql:/docker-entrypoint-initdb.d/schema.sql


  backend:
    build: .
    container_name: backend_application
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3005:3005"
    depends_on:
      - db
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - ./package.json:/app/package.json


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    

volumes:
  postgres_database:
  node_modules:
