version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: Matcha_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: backend_app
    restart: always
    environment:
      DATABASE_URL: postgres://root:12345@db:5432/Matcha_db
    ports:
      - "3000:3000"  # Exposer le port de l'application
      - "5555:5555"  # Exposer le port de Prisma Studio
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
